name: hyperdiff
channels:
  - conda-forge
dependencies:
  # ──Python & 科學運算──
  - python=3.11
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - networkx
  - tqdm

  # ──C++/Python 介面 & 編譯鏈──
  - eigen         # Eigen 3.x
  - pybind11      # 供 setup.py include
  - cxxopts       # CLI parser
  - cmake
  - make
  # - gxx_linux-64  # GNU C++20（WSL）
  #  ↓ 若純 Windows，改裝 m2‑msys2 或直接用 Visual Studio Build Tools
  #  - vs2019_win-64

  # ──(選) GPU Torch──
  # - pytorch
  # - torchvision
  # - torchaudio
  # - pytorch-cuda=11.8
